### ISSUE TITLE
Keyboard not recognised by Multiboard

### ISSUE THREAD

**Issue by Somull** [Tygo-bear/MultiBoard#25]
Hello, I followed you guide and got the hardware you suggested.
I went through all the steps, added an UUID to the sketch, moved the library to its folder in documents, uploaded all to the board
but Multiboard doesn't recognise the keyboard in auto nor manually adding the COM port + UUID.

I don't know if the hardware should be recognised as HID in Control Panel, but it is still recognised as "Arduino".

Any tips?

Thank you very much
Andrea

**Comment by Tygo-bear** [comment]
Please provide the log file. You can find it at "%appdata%\MultiBoard\logs"
Or go to settings in MultiBoard and select the info tab, and click open log.
![image](https://user-images.githubusercontent.com/26803517/107155945-ba27da80-697b-11eb-8dc8-a5be0babd153.png)

**Comment by gitbork** [comment]
I wanted to chime in that this same exact thing was happening to me last week, but then when I tried it again today the application detected my keyboard. I didn't change anything between last week and today. I didn't change the Arduino sketch, I didn't upload a new compiled sketch to the Arduino. I used the same keyboard, cables, and Arduino and USB host shield as last week. And I didn't do anything to the installed Multiboard app (no reinstall etc.)

It's a complete mystery to me why it would start working now. This isn't helpful to anybody here, but at least it confirms that this is an issue in the wild.

One other thing I noticed when it was not working was that even if I compiled the default sketch for USBHIDBootKbd (the one that is an example in the Arduino IDE) the keystrokes were not being forwarded to the computer in a manner that allowed text input in Notepad. But the keystrokes were being properly registered and detected when looking at the serial console in the Arduino IDE. 

I'm somewhat scared to try replicating that now that things appear to mostly be working though lol.

**Comment by Tygo-bear** [comment]
You can change some settings to improve the keyboard detection
- Put "Connection time out delay" to max
- Turn off "Keyboard scan SAFE MODE"
![image](https://user-images.githubusercontent.com/26803517/107292185-b3779100-6a69-11eb-954d-be4fcca8917d.png)

**Comment by Somull** [comment]
Thanks for all your tips.

I've actually realised that arduino is getting no inputs from the keyboard with the sketch provided nor with the library examples.

I thought it was a power issue due to backlighted keyboard (5V 500mA) but even an AC adapter hasn't solved the problem (all the system drains only around 250mA from AC though). Unfortunatly I got 2 keyboard of the same model so I can't try another one.

I think at this point I should write in the USB library repository.


> 
> 
> Please provide the log file. You can find it at "%appdata%\MultiBoard\logs"
> Or go to settings in MultiBoard and select the info tab, and click open log.
> ![image](https://user-images.githubusercontent.com/26803517/107155945-ba27da80-697b-11eb-8dc8-a5be0babd153.png)

```
 --DEBUG STARTED--
 Construction main done
 COM ports scan mode 2
 --comports--
    comports: COM4
    comports: COM3
    comports: COM15
 --scan results--
    COM4 result: NONE
    COM3 result: NONE
    COM15 result: NONE
 loading boards
 loading: C:\Users\Andrea\AppData\Roaming\MultiBoard\saves\7dc5d7f8-6a71-11eb-9439-0242ac130002.mkb
 loading keyboard 7dc5d7f8-6a71-11eb-9439-0242ac130002
 test --> not found!


```
