### ISSUE TITLE
AHK Duplicate function definition error

### ISSUE THREAD

**Issue by gitbork** [Tygo-bear/MultiBoard#26]
**Describe the bug**
Simple AHK scrip causes a "Duplicate Function Definition Error" and will not run when bound to hotkey. I have a simple AHK test script that is meant to launch calculator. This script will run fine if I right click and "Run Script". It will also run fine using the shortcut key that I have defined in Multiboard - however it will only do so one time. After the first time the hotkey launches the calculator application the first time it will no longer work. The subsequent times I try to use the defined shortcut key I get the following error:

![multiboard_AHK_error_duplicate](https://user-images.githubusercontent.com/26959898/107285573-ff541700-6a24-11eb-9fca-80a1962051ba.PNG)

This same sort of error happens for any AHK script that has any kind of function defined.

Here is the code I am using to launch the calculator:

`Calculator(){
	Run Calc.exe
	return
}

Calculator()`

**To Reproduce**
1. create simple calculator.ahk using code above
2. Assign that AHK file to a key
3. Save Multiboard config
4. Use new calculator shortcut key
5. Close Calculator app
6. Use the new calculator shortcut key a second time
7. Behold the error message.

**Expected behavior**
The calculator should launch when pushing the defined shortcut key. (Really any AHK script with a function defined in it should work)

**Log**

--DEBUG STARTED--
Construction main done
COM ports scan mode 2
--comports--
   comports: COM1
   comports: COM3
--scan results--
   COM1 result: NONE
   COM3 result: 9ba53aba-246d-4b26-9d7d-df2a61e74adb
loading boards
loading: C:\Users\choke\AppData\Roaming\MultiBoard\saves\9ba53aba-246d-4b26-9d7d-df2a61e74adb.mkb
loading keyboard 9ba53aba-246d-4b26-9d7d-df2a61e74adb
try check valid connection from COM3 attempt 0
valid connection on COM3

**Screenshots**
Here is the Multiboard config
![image](https://user-images.githubusercontent.com/26959898/107286086-ba7cb000-6a25-11eb-851b-79232c75b89a.png)

Here is the "Run Script" method that will work all the time
![runScript](https://user-images.githubusercontent.com/26959898/107286268-fadc2e00-6a25-11eb-96de-913eb9809c74.png)

Here is the AHK Code again:
![image](https://user-images.githubusercontent.com/26959898/107286339-12b3b200-6a26-11eb-95d3-29fca36d3661.png)

Here is the crappy error:
![multiboard_AHK_error_duplicate](https://user-images.githubusercontent.com/26959898/107286367-1cd5b080-6a26-11eb-8abb-501eaa41a770.PNG)

**Additional Info (please complete the following information):**
 - OS: Windows 10
 - MultiBoard detects keyboard: YES

**Additional context**
I can get calculator to launch by doing it this way, but that doesn't help me figure out the bigger problem about why any AAHK script that uses the "define function" method doesn't work...
![image](https://user-images.githubusercontent.com/26959898/107286579-62927900-6a26-11eb-8f72-8ef9c868d65e.png)

**Comment by Tygo-bear** [comment]
This is indeed a bug. It should be fixed in the next release (v1.0.2.0). Wich is planned to be released coming weeks.

**Comment by Tygo-bear** [comment]
I looked more closely at the bug. I can not fix it properly because of the AutoHotkey.Interop library. The library doesn't support multithreading with AHK. 
There is an alternative fix. But it creates too much instability. Therefore I won't roll this out into the main release. currently, I will mark this as "won't fix" until the AutoHotkey.Interop is updated to support AHKThreading or a better solution presents itself.

**Comment by Tygo-bear** [comment]
There will be a new release of MultiBoard (v1.0.1.8) that can resolve your issue. In version 1.0.1.8 is it possible the declare a global function that can be used within MultiBoard keys and invoked without the duplicate error (#30). You can try out the new release on the "new-release" branch by running [Mulitboard_setup.exe](https://github.com/Tygo-bear/MultiBoard/blob/new-release/MultiBoard_setup.exe)

v1.0.1.8 seems stable and will be pushed to the master soon.

If you want to try out the new preload system. you just add your calculator function in the "preload.ahk" file. The preload.ahk file can be located at "%appdata%/MultiBoard" or just navigate to setting > info > open save file.

![image](https://user-images.githubusercontent.com/26803517/117002587-07e68180-ace4-11eb-91be-5fb33f6aa7bb.png)

And bind a key to this AHK code:
![image](https://user-images.githubusercontent.com/26803517/117002654-20569c00-ace4-11eb-9118-b11006de94ea.png)
