### ISSUE TITLE
My board is not detected in newer version from 1.0.1.5

### ISSUE THREAD

**Issue by dorgesilas** [Tygo-bear/MultiBoard#33]
it just won't detect it, another bug I discovered is I can't delete a keyboard I manually detect, (which doesn't work anyways  because for some reason it just can't detect it)

it works perfectly in 1.0.1.5, but I can't run hotkeys in that version or I'm just too dumb to find out

**Comment by Tygo-bear** [comment]
From v1.0.1.6 there is a setting, which limits com port search. It can be turned off.
![image](https://user-images.githubusercontent.com/26803517/117258938-d2f63e00-ae4d-11eb-93f3-59714e6fb75f.png)
Just turn off "keyboard scan SAFE MODE".

**Comment by dorgesilas** [comment]
hey there, sorry for bein a bit noob but this works, thank you so much sir!

I now would like to ask my 2nd question, now this is not a bug (maybe?)

it seems the hotkey creator doesn't work very well

attached pic 
![InputCmd](https://user-images.githubusercontent.com/17200688/117265698-b292a780-ae7e-11eb-9872-13512576d653.JPG)

as per image, I tried to make a combination of {{Windows key}} {{shift}} {{2}} and after that maybe it decided to put {{winUP}} by itself, but after using keyboard test it seems to only detect {{shift}}

**Comment by Tygo-bear** [comment]
**This is indeed a bug**. The hotkey generator makes a code generation error. the outer "{}" are incorrect. I hope to get it fixed in the next release(next week). but it should work if you just paste that line in an AHK file without the outer "{}".
